---
title: "MLR for Prediction of Prepayment Amount"
author: "Sungsu Jeong"
date: "7/28/2021"
output: html_document
---

```{r setup, include=FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(moments)
library(UsingR)
library(stats)
library(DescTools)
library(lmtest)
library(readxl)
library(magrittr)
library(car)
library(nortest)
library(EnvStats)
library(Metrics)
library(writexl)
```

```{r}
# 01 Load dataset
df <- read_excel('loan_fp01.xlsx')
View(df)
```

```{r}
# 02 Split data into training and test dataset
train <- df %>%
  sample_frac(0.7)

df <- df %>%
  mutate(id = row_number())

test <- df %>%
  anti_join(train, by = 'id')
```

```{r}
# 03 Build a starting MLR
mlr.mod <- lm(diff_pymnt ~ funded_amnt + factor(term) + int_rate + factor(grade) +
                      pct_fund + pct_inv + delinq_2yrs + inq_last_6mths +
                      mths_since_last_delinq + pub_rec + factor(initial_list_status) +
                      acc_now_delinq + annual_inc + dti + factor(emp_length) +
                      pymnt_period + factor(prepymnt) + factor(purpose) + 
                      factor(home_ownership) + factor(verification_status) + 
                      factor(pymnt_status), data=train)
summary(mlr.mod)
```

```{r}
# 04 Model selection: backward with AIC
empty.model <- lm(diff_pymnt ~ 1, data=train)
full.model <- lm(diff_pymnt ~ funded_amnt + factor(term) + int_rate + factor(grade) +
                   pct_fund + pct_inv + delinq_2yrs + inq_last_6mths +
                   mths_since_last_delinq + pub_rec + factor(initial_list_status) +
                   acc_now_delinq + annual_inc + dti + factor(emp_length) +
                   pymnt_period + factor(prepymnt) + factor(purpose) + 
                   factor(home_ownership) + factor(verification_status) + 
                   factor(pymnt_status), data=train)

back.mod <- step(full.model, 
                 scope=list(lower=empty.model,
                            upper=full.model),
                 direction="backward", k=qchisq(0.001, 1, lower.tail=F))
```

```{r}
# 05 Model selected by backward elimination
mlr.mod00 <- lm(diff_pymnt ~ funded_amnt + factor(term) + factor(grade) +
                             factor(initial_list_status) + factor(pymnt_status) +
                             pymnt_period + factor(home_ownership) + 
                             factor(verification_status), data=train)
summary(mlr.mod00)
vif(mlr.mod00)
```

```{r}
# 06 Final Model selection
mlr.mod01 <- lm(diff_pymnt ~ poly(funded_amnt, 2, raw=T) + factor(term) + 
                  pymnt_period + factor(term):pymnt_period + 
                  funded_amnt:pymnt_period + funded_amnt:factor(grade), data=train)
summary(mlr.mod01)
vif(mlr.mod01)
```

```{r}
# 07 Score a test dataset
pred01 <- predict(mlr.mod01, newdata=test)

# 08 Compute MAE
mae(test$diff_pymnt, pred01)
```

```{r}
# 09 Load dataset that contains current loan cases
df1 <- read_excel('loan_c.xlsx')
```

```{r}
# 10 Score the new dataset and add predicted results 
pred_diff_pymnt <- predict(mlr.mod01, newdata=df1)
df1 <- cbind(pred_diff_pymnt, df1)
```

```{r}
# 11 Export an excel file for visualization
write_xlsx(df1, "C:/Users/sjeong5/Documents/loan_new_pred.xlsx")
```
